### ISSUE TITLE
版本兼容问题

### ISSUE THREAD

**Issue by Cai-Go** [codyer/ElegantBus-example#1]
java.lang.NoSuchMethodError: No static method getProcessName() Ljava/lang/String; in class Landroid/app/Application; or its super classes (declaration of 'android.app.Application' appears in /system/framework/framework.jar)

getProcessName()这个方法在9.0以下的手机上无效，导致应用崩溃。
![image](https://user-images.githubusercontent.com/7565399/88039584-57efbf80-cb7a-11ea-976d-0bcb89195ed0.png)

**Comment by codyer** [comment]
> java.lang.NoSuchMethodError: No static method getProcessName() Ljava/lang/String; in class Landroid/app/Application; or its super classes (declaration of 'android.app.Application' appears in /system/framework/framework.jar)
> 
> getProcessName()这个方法在9.0以下的手机上无效，导致应用崩溃。
> ![image](https://user-images.githubusercontent.com/7565399/88039584-57efbf80-cb7a-11ea-976d-0bcb89195ed0.png)

已经修复，请使用2.1.0
